name: notarize-project-bom

on:
  push:
    branches: [main]

jobs:
  notarize-nodejs-project-with-bom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Notarize Node.js project with BoM
        #--> Run the GitHub action
        uses: codenotary/vcn-notarize-bom-nodejs-github-action@v1.0.0
        # uses: codenotary/vcn-notarize-bom-nodejs-github-action@main
        with:
          asset: git://.
          cnil_host: ${{ secrets.CNIL_HOST }}
          cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
          cnil_api_key: ${{ secrets.CNIL_API_KEY }}
        #<--
        #--> or run the vcn Docker image directly (all vcn flags are available and passed through)
        # uses: docker://codenotary/vcn:bom-nodejs
        # with:
        #   args: n git://. --lc-host ${{ secrets.CNIL_HOST }} --lc-port ${{ secrets.CNIL_GRPC_PORT }} --lc-api-key ${{ secrets.CNIL_API_KEY }} --bom
        #<--
